### ISSUE TITLE
Compilation fails after commit 661f1620e3a261d4b32fc5987acc322d59fcc874

### ISSUE THREAD

**Issue by dp1** [io12/pwninit#84]
I tried to compile from source, but it seems that the updated reqwest version breaks the code. When compiling the previous commit everything works fine, but from 661f1620e3a261d4b32fc5987acc322d59fcc874 onwards I get these errors:

```
error[E0599]: no method named `context` found for opaque type `impl Future` in the current scope
  --> src/libc_deb.rs:73:34
   |
73 |     let resp = reqwest::get(url).context(DownloadError)?;
   |                                  ^^^^^^^ method not found in `impl Future`

error[E0277]: the trait bound `Response: std::io::Read` is not satisfied
  --> src/libc_deb.rs:99:36
   |
99 |     let mut deb = ar::Archive::new(deb_bytes);
   |                                    ^^^^^^^^^ the trait `std::io::Read` is not implemented for `Response`
   |
   = note: required by `ar::Archive::<R>::new`

error[E0277]: the trait bound `Response: std::io::Read` is not satisfied
   --> src/libc_deb.rs:99:19
    |
99  |     let mut deb = ar::Archive::new(deb_bytes);
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::io::Read` is not implemented for `Response`
    | 
   ::: /home/dario/.cargo/registry/src/github.com-1ecc6299db9ec823/ar-0.8.0/src/lib.rs:437:23
    |
437 | pub struct Archive<R: Read> {
    |                       ---- required by this bound in `ar::Archive`

error[E0599]: the method `next_entry` exists for struct `ar::Archive<Response>`, but its trait bounds were not satisfied
   --> src/libc_deb.rs:102:37
    |
102 |     while let Some(Ok(entry)) = deb.next_entry() {
    |                                     ^^^^^^^^^^ method cannot be called on `ar::Archive<Response>` due to unsatisfied trait bounds
    | 
   ::: /home/dario/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/response.rs:24:1
    |
24  | pub struct Response {
    | ------------------- doesn't satisfy `Response: std::io::Read`
    |
    = note: the following trait bounds were not satisfied:
            `Response: std::io::Read`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `pwninit`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

(Changing reqwest back to 0.9.22 makes everything work with the latest commit as well)

**Comment by io12** [comment]
Fixed, thanks!
